import { describe, it, expect, beforeEach, vi } from 'vitest';
import { useChatStore } from '@/lib/store/chat-store';
import { extractCode } from '@/lib/extract-code';

describe('Chat Flow Integration (Store + API)', () => {
  beforeEach(() => {
    // Reset the store before each test run
    useChatStore.setState({
      chats: [],
      currentChatId: null,
      artifacts: [],
    });
  });

  it('should process full flow: create chat, receive response, create artifact, edit and regenerate versions, then cascade delete', async () => {
    const store = useChatStore.getState();

    // 1. Create a new chat
    store.createChat('gemini-3-flash');
    let state = useChatStore.getState();
    expect(state.chats.length).toBe(1);
    const chatId = state.chats[0].id;
    expect(state.currentChatId).toBe(chatId);

    // 2. Mock sending user message
    const userMessage = {
      id: 'msg-user-1',
      role: 'user' as const,
      content: 'Generate a basic D3 canvas',
      timestamp: new Date(),
    };

    useChatStore.getState().addMessage(chatId, userMessage);
    state = useChatStore.getState();
    expect(state.chats[0].messages.length).toBe(1);

    // 3. Simulate calling API and receiving assistant response containing D3 code block
    // (mock response defined in test/mocks/handlers.ts for */api/chat)
    const mockApiResponse = {
      message: {
        role: 'assistant' as const,
        content: 'Mocked assistant response with code block:\n\n```javascript\n// renderer: d3\nconst a = 1;\n```',
        tokens: 30
      }
    };

    // Add assistant response to the store
    const assistantMessage = {
      id: 'msg-assistant-1',
      role: mockApiResponse.message.role,
      content: mockApiResponse.message.content,
      timestamp: new Date(),
      tokens: mockApiResponse.message.tokens,
    };

    useChatStore.getState().addMessage(chatId, assistantMessage);
    state = useChatStore.getState();
    expect(state.chats[0].messages.length).toBe(2);

    // 4. Verify code block is parsed and artifact is created in store
    const extracted = extractCode(assistantMessage.content);
    expect(extracted).not.toBeNull();
    expect(extracted?.renderer).toBe('d3');
    expect(extracted?.code).toBe('// renderer: d3\nconst a = 1;');

    if (extracted) {
      useChatStore.getState().addArtifact({
        chatId,
        chatTitle: state.chats[0].title,
        code: extracted.code,
        renderer: extracted.renderer,
        createdAt: new Date(),
      });
    }

    state = useChatStore.getState();
    expect(state.artifacts.length).toBe(1);
    expect(state.artifacts[0].renderer).toBe('d3');

    // 5. Simulate edit/regenerate version logic
    // Edit message by adding version branching details
    const assistantMessageV2 = {
      id: 'msg-assistant-2',
      role: 'assistant' as const,
      content: 'Second version code block:\n\n```javascript\n// renderer: d3\nconst a = 2;\n```',
      timestamp: new Date(),
      tokens: 35,
    };

    // Store version history on the original assistant message node
    useChatStore.getState().addMessage(chatId, assistantMessageV2);
    
    // Retrieve the actual assistant message ID generated by the store
    const assistantMsgId = useChatStore.getState().chats[0].messages[1].id;

    // Simulate updating active versions lists in message node
    const updatedMessages = useChatStore.getState().chats[0].messages.map(m => {
      if (m.id === assistantMsgId) {
        return {
          ...m,
          versions: ['// renderer: d3\nconst a = 1;', '// renderer: d3\nconst a = 2;'],
          activeVersionIdx: 1,
        };
      }
      return m;
    });

    useChatStore.setState({
      chats: useChatStore.getState().chats.map(c => c.id === chatId ? { ...c, messages: updatedMessages } : c)
    });

    state = useChatStore.getState();
    const updatedMessage = state.chats[0].messages.find(m => m.id === assistantMsgId);
    expect(updatedMessage?.versions?.length).toBe(2);
    expect(updatedMessage?.activeVersionIdx).toBe(1);

    // 6. Delete chat and verify cascade deletions are performed correctly
    useChatStore.getState().deleteChat(chatId);
    state = useChatStore.getState();
    expect(state.chats.length).toBe(0);
    expect(state.artifacts.length).toBe(0);
    expect(state.currentChatId).toBeNull();
  });
});
